export const reviewsTableData = [
  {
    id: 1,
    // used by AdminFiled
    name: 'John Doe',
    email: 'john.doe@example.com',
    avatar: 'https://i.pravatar.cc/40?img=1',
    device_id: 'DEV-001-AUS',
    office_name: 'Sydney Office',
    created_at: '2025-09-10T10:30:00Z',
    room_type: 'Private Room',
    status: 'pending',
    installation_status: 'pending',
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    avatar: 'https://i.pravatar.cc/40?img=2',
    device_id: 'DEV-002-UK',
    office_name: 'London HQ',
    created_at: '2025-08-25T15:00:00Z',
    room_type: 'Shared Room',
    status: 'completed',
    installation_status: 'completed',
  },
  {
    id: 3,
    name: 'Alex Johnson',
    email: 'alex.johnson@example.com',
    avatar: 'https://i.pravatar.cc/40?img=3',
    device_id: 'DEV-003-USA',
    office_name: 'New York Office',
    created_at: '2025-09-01T09:15:00Z',
    room_type: 'Deluxe Suite',
    status: 'unsubmitted',
    installation_status: 'unsubmitted',
  },
  {
    id: 4,
    name: 'Emily Brown',
    email: 'emily.brown@example.com',
    avatar: 'https://i.pravatar.cc/40?img=4',
    device_id: 'DEV-004-AUS',
    office_name: 'Melbourne Branch',
    created_at: '2025-09-12T18:45:00Z',
    room_type: 'Twin Room',
    status: 'pending',
    installation_status: 'pending',
  },
  {
    id: 5,
    name: 'Michael Lee',
    email: 'michael.lee@example.com',
    avatar: 'https://i.pravatar.cc/40?img=5',
    device_id: 'DEV-005-CA',
    office_name: 'Toronto Office',
    created_at: '2025-09-05T12:20:00Z',
    room_type: 'Private Room',
    status: 'completed',
    installation_status: 'completed',
  },
  {
    id: 6,
    name: 'Michael Lee',
    email: 'michael.lee@example.com',
    avatar: 'https://i.pravatar.cc/40?img=5',
    device_id: 'DEV-005-CA',
    office_name: 'Toronto Office',
    created_at: '2025-09-05T12:20:00Z',
    room_type: 'Private Room',
    status: 'unsubmitted',
    installation_status: 'unsubmitted',
  },
  {
    id: 6,
    name: 'Michael Lee',
    email: 'michael.lee@example.com',
    avatar: 'https://i.pravatar.cc/40?img=5',
    device_id: 'DEV-005-CA',
    office_name: 'Toronto Office',
    created_at: '2025-09-05T12:20:00Z',
    room_type: 'Private Room',
    status: 'awaiting_review',
    installation_status: 'awaiting_review',
  },
];
