import { AiFillTool,AiOutlineTool } from 'react-icons/ai';
import { FaDownload } from 'react-icons/fa';
import {HiOutlineReceiptRefund, HiReceiptRefund } from 'react-icons/hi';
import { IoMdTime } from 'react-icons/io';
import { LuChartSpline,LuPackage } from 'react-icons/lu';
import {
  MdDashboard,
  MdOutlineDashboard,
  MdOutlineKeyboardCommandKey,
  MdOutlineSdCardAlert,
  MdSdCardAlert,
} from 'react-icons/md';
import {
  PiPackageFill,
  PiScanDuotone,
  PiScanFill,
  PiUsersThreeBold,
  PiUsersThreeFill,
  PiWalletBold,
  PiWalletFill,
} from 'react-icons/pi';
import { RiExchangeDollarLine, RiMoneyDollarCircleFill } from 'react-icons/ri';
import { TbUsers } from 'react-icons/tb';

export const NAV_CONFIG = {
  super_admin: [
    {
      key: '1',
      label: 'dashboard',
      ActiveIcon: MdDashboard,
      InactiveIcon: MdOutlineDashboard,
      link: '/super-admin/dashboard',
      matchPaths: ['/super-admin/dashboard'],
    },
    {
      key: '2',
      label: 'users',
      ActiveIcon: PiUsersThreeFill,
      InactiveIcon: PiUsersThreeBold,
      link: '/super-admin/users',
      matchPaths: [
        '/super-admin/users',
        '/super-admin/users/distributor-deal/*',
        '/super-admin/users/distributor-deal/details/*',
        '/super-admin/users/distributor-deal/new-deal/*',
      ],
      innerPages: {
        '/distributor-deal/:id': 'Distributor Deal',
        '/distributor-deal/details/:id': 'Deal Details',
        '/distributor-deal//new-deal/:id': 'New Deal',
      },
    },
    {
      key: '3',
      label: 'Subscribed Users',
      ActiveIcon: RiMoneyDollarCircleFill,
      InactiveIcon: RiExchangeDollarLine,
      link: '/super-admin/subscribed-users',
      matchPaths: ['/super-admin/subscribed-users'],
    },
    {
      key: '4',
      label: 'Reviews',
      ActiveIcon: PiScanFill,
      InactiveIcon: PiScanDuotone,
      link: '/super-admin/reviews',
      matchPaths: ['/super-admin/reviews', '/super-admin/reviews/details/:elderly_id/:room_id'],
      innerPages: {
        '/super-admin/reviews/details/:elderly_id/:room_id': 'Details',
      },
    },
    {
      key: '5',
      label: 'Payment History',
      ActiveIcon: PiWalletFill,
      InactiveIcon: PiWalletBold,
      link: '/super-admin/payment-history',
      matchPaths: ['/super-admin/payment-history'],
    },
    {
      key: '6',
      label: 'refunds request',
      ActiveIcon: HiReceiptRefund,
      InactiveIcon: HiOutlineReceiptRefund,
      link: '/super-admin/refunds-request',
      matchPaths: ['/super-admin/refunds-request'],
    },
  ],
  supports_agent: [
    {
      key: '1',
      label: 'dashboard',
      ActiveIcon: MdDashboard,
      InactiveIcon: MdOutlineDashboard,
      link: '/supporter/support-agent/dashboard',
      matchPaths: ['/supporter/support-agent/dashboard'],
    },
    {
      key: '2',
      label: 'users',
      ActiveIcon: PiUsersThreeFill,
      InactiveIcon: PiUsersThreeBold,
      link: '/supporter/elderlies',
      matchPaths: ['/supporter/elderlies', '/supporter/elderlies/elderly-profile/*'],
      innerPages: {
        '/elderly-profile/:id': 'User Profile',
      },
    },
    {
      key: '3',
      label: 'Alerts history',
      ActiveIcon: MdSdCardAlert,
      InactiveIcon: MdOutlineSdCardAlert,
      link: '/supporter/alerts',
      matchPaths: ['/supporter/alerts'],
    },
  ],
  monitoring_agency: [
    {
      key: '1',
      label: 'dashboard',
      ActiveIcon: MdDashboard,
      InactiveIcon: MdOutlineDashboard,
      link: '/support-nurnt/dashboard',
      matchPaths: ['/support-nurnt/dashboard'],
    },
    {
      key: '2',
      label: 'users',
      ActiveIcon: PiUsersThreeFill,
      InactiveIcon: PiUsersThreeBold,
      link: '/supporter/elderlies',
      matchPaths: ['/supporter/elderlies', '/supporter/elderlies/elderly-profile/*'],
      innerPages: {
        '/elderly-profile/:id': 'User Profile',
      },
    },
    {
      key: '3',
      label: 'Alerts history',
      ActiveIcon: MdSdCardAlert,
      InactiveIcon: MdOutlineSdCardAlert,
      link: '/supporter/alerts',
      matchPaths: ['/supporter/alerts'],
    },
  ],
  nurse: [
    {
      key: '1',
      label: 'Live Dashboard',
      ActiveIcon: MdOutlineKeyboardCommandKey,
      InactiveIcon: MdOutlineKeyboardCommandKey,
      link: '/supporter/nurse/dashboard',
      matchPaths: ['/supporter/nurse/dashboard'],
    },
    {
      key: '2',
      label: 'Compliance',
      ActiveIcon: LuChartSpline,
      InactiveIcon: LuChartSpline,
      link: '/supporter/compliance',
      matchPaths: ['/supporter/compliance'],
    },
    {
      key: '3',
      label: 'Residents',
      ActiveIcon: TbUsers,
      InactiveIcon: TbUsers,
      link: '/supporter/elderlies',
      matchPaths: ['/supporter/elderlies', '/supporter/elderlies/elderly-profile/*'],
      innerPages: {
        '/elderly-profile/:id': 'User Profile',
      },
    },
    {
      key: '4',
      label: 'Alerts History',
      ActiveIcon: IoMdTime,
      InactiveIcon: IoMdTime,
      link: '/supporter/alerts',
      matchPaths: ['/supporter/alerts'],
    },
    {
      key: '5',
      label: 'Export Compliance',
      ActiveIcon: FaDownload,
      InactiveIcon: FaDownload,
      link: '/supporter/export-compliance',
      matchPaths: ['/supporter/export-compliance'],
    },
  ],
  end_user: [
    {
      key: '1',
      label: 'dashboard',
      ActiveIcon: MdDashboard,
      InactiveIcon: MdOutlineDashboard,
      link: '/supporter/end-user/dashboard',
      matchPaths: ['/supporter/end-user/dashboard'],
    },
    {
      key: '2',
      label: 'users',
      ActiveIcon: PiUsersThreeFill,
      InactiveIcon: PiUsersThreeBold,
      link: '/supporter/elderlies',
      matchPaths: ['/supporter/elderlies', '/supporter/elderlies/elderly-profile/*'],
      innerPages: {
        '/elderly-profile/:id': 'User Profile',
      },
    },
    {
      key: '3',
      label: 'Alerts history',
      ActiveIcon: MdSdCardAlert,
      InactiveIcon: MdOutlineSdCardAlert,
      link: '/supporter/alerts',
      matchPaths: ['/supporter/alerts'],
    },
  ],
  monitoring_station: [
    {
      key: '1',
      label: 'dashboard',
      ActiveIcon: MdDashboard,
      InactiveIcon: MdOutlineDashboard,
      link: '/support-nurnt/dashboard',
      matchPaths: ['/support-nurnt/dashboard'],
    },
    {
      key: '2',
      label: 'users',
      ActiveIcon: PiUsersThreeFill,
      InactiveIcon: PiUsersThreeBold,
      link: '/support-nurnt/dashboard/suspended-user',
      matchPaths: ['/support-nurnt/dashboard/suspended-user'],
    },
    {
      key: '3',
      label: 'orders',
      ActiveIcon: PiPackageFill,
      InactiveIcon: LuPackage,
      link: '/support-nurnt/dashboard/orders',
      matchPaths: ['/support-nurnt/dashboard/orders'],
    },
  ],
  // distributor: [
  //   {
  //     key: "1",
  //     label: "Dashboard",
  //     ActiveIcon: MdDashboard,
  //     InactiveIcon: MdOutlineDashboard,
  //     link: "/management/dashboard",
  //     matchPaths: ["/management/dashboard"],
  //   },
  //   {
  //     key: "2",
  //     label: "Customers",
  //     ActiveIcon: PiUsersThreeFill,
  //     InactiveIcon: PiUsersThreeBold,
  //     link: "/management/customers",
  //     matchPaths: ["/management/customers"],
  //   },
  //   {
  //     key: "3",
  //     label: "Orders",
  //     ActiveIcon: IoCart,
  //     InactiveIcon: IoCartOutline,
  //     link: "/management/orders",
  //     matchPaths: ["/management/orders"],
  //   },
  //   {
  //     key: "4",
  //     label: "Devices",
  //     ActiveIcon: HiOutlineDeviceMobile,
  //     InactiveIcon: HiOutlineDeviceMobile,
  //     link: "/management/devices",
  //     matchPaths: ["/management/devices"],
  //   }
  // ],
  distributor: [
    {
      key: '1',
      label: 'dashboard',
      ActiveIcon: MdDashboard,
      InactiveIcon: MdOutlineDashboard,
      link: '/support-nurnt/dashboard',
      matchPaths: ['/support-nurnt/dashboard'],
    },
    {
      key: '2',
      label: 'users',
      ActiveIcon: PiUsersThreeFill,
      InactiveIcon: PiUsersThreeBold,
      link: '/support-nurnt/dashboard/suspended-user',
      matchPaths: ['/support-nurnt/dashboard/suspended-user'],
    },
    {
      key: '3',
      label: 'deals',
      ActiveIcon: PiPackageFill,
      InactiveIcon: LuPackage,
      link: '/support-nurnt/dashboard/deals',
      matchPaths: ['/support-nurnt/dashboard/deals'],
    },
  ],
  office: [
    {
      key: '1',
      label: 'dashboard',
      ActiveIcon: MdDashboard,
      InactiveIcon: MdOutlineDashboard,
      link: '/support-nurnt/dashboard',
      matchPaths: ['/support-nurnt/dashboard'],
    },
    {
      key: '2',
      label: 'users',
      ActiveIcon: PiUsersThreeFill,
      InactiveIcon: PiUsersThreeBold,
      link: '/support-nurnt/dashboard/suspended-user',
      matchPaths: ['/support-nurnt/dashboard/suspended-user'],
    },
    {
      key: '3',
      label: 'deals',
      ActiveIcon: PiPackageFill,
      InactiveIcon: LuPackage,
      link: '/support-nurnt/dashboard/deals',
      matchPaths: ['/support-nurnt/dashboard/deals'],
    },
  ],
  installer: [
    {
      key: '1',
      label: 'dashboard',
      ActiveIcon: MdDashboard,
      InactiveIcon: MdOutlineDashboard,
      link: '/support-nurnt/dashboard',
      matchPaths: ['/support-nurnt/dashboard'],
    },
    {
      key: '2',
      label: 'installation',
      ActiveIcon: AiFillTool,
      InactiveIcon: AiOutlineTool,
      link: '/support-nurnt/dashboard/installation',
      matchPaths: ['/support-nurnt/dashboard/installation'],
    },
  ],
  others: [
    {
      key: '1',
      label: 'dashboard',
      ActiveIcon: MdDashboard,
      InactiveIcon: MdOutlineDashboard,
      link: '/support-nurnt/dashboard',
      matchPaths: ['/support-nurnt/dashboard'],
    },
    {
      key: '2',
      label: 'users',
      ActiveIcon: PiUsersThreeFill,
      InactiveIcon: PiUsersThreeBold,
      link: '/support-nurnt/dashboard/suspended-user',
      matchPaths: ['/support-nurnt/dashboard/suspended-user'],
    },
  ],
};
