export const QUERY_KEYS = {
  ALERTS: ['alerts'],
  PICKALERT: ['pcikalert'],
  CUSTOMER: ['customers'],
  CUSTOMER_DETAILS: (id) => ['customer', id],
  FALLPLAYBACK: (id) => ['fallplayback', id],
  ROOMINFO: (id) => ['roominfo', id],
  SENDSMS: ['sendsms'],
  SENDNOTIFICATION: ['sendnotification'],
  ALERTLOG: ['alertlogs'],
  PERFORMANCESCORE: ['performancescore'],
  DEACTIVATEDCUSTOMER: ['dactivatedcustomer'],
  COUNT_STATISTICS: ['countstatistics'],
  AGENT_COUNT_STATISTICS: ['agentCountstatistics'],
  TOTAL_ALERTS: ['totalalerts'],
  TOTAL_ALERTS_TREND: ['totalalertstrend'],
  SLA_STATISTICS: ['slastatistics'],
  AGENT_PERFORMANCE: ['agentperformance'],
  RESOLVED_BY_ME: ['resolvedbyme'],
  USERS: ['users'],
  USERS_DETAILS: (id) => ['user', id],
  TRUE_FALSE_ALERTS: ['trueFalseAlerts'],
  STATISTICS_BY_ID: (id) => ['statisticsById', id],
  GET_COUNTRY: ['getCountry'],
  GET_MONITORING_COMPANY_CONF: (id) => ['getMonitoringCompanyConf', id],
  SET_ALERT_LOG: ['setAlertLog'],
};
