export const alerts = [
  {
    id: 1,
    type: 'Fall Detected',
    time: '08:00 PM, 20 Sep 2025',
    location: 'Bedroom',
    address: '456 Elm Street, Suite 3, Los Angeles, United States',
    life: '46s',
    status: 'Unpicked',
    name: 'Majharul',
  },
  {
    id: 2,
    type: 'Device Offline',
    time: '08:10 PM, 20 Sep 2025',
    location: 'Living Room',
    address: '123 Main Street, NY',
    life: '1m36s',
    status: 'Picked by you',
    name: 'Jisan Ahmed',
  },
  {
    id: 3,
    type: 'Device Offline',
    time: '08:20 PM, 20 Sep 2025',
    location: 'Office',
    address: '789 Maple Ave, CA',
    life: '2m05s',
    status: 'Picked by others',
    name: 'Kaisar Ahmed',
  },
  {
    id: 4,
    type: 'Device Offline',
    time: '08:20 PM, 20 Sep 2025',
    location: 'Office',
    address: '789 Maple Ave, CA',
    life: '2m05s',
    status: 'Picked by others',
    name: 'Kaisar Ahmed',
  },
  {
    id: 5,
    type: 'Device Offline',
    time: '08:20 PM, 20 Sep 2025',
    location: 'Office',
    address: '789 Maple Ave, CA',
    life: '2m05s',
    status: 'Picked by others',
    name: 'Kaisar Ahmed',
  },
  {
    id: 6,
    type: 'Device Offline',
    time: '08:20 PM, 20 Sep 2025',
    location: 'Office',
    address: '789 Maple Ave, CA',
    life: '2m05s',
    status: 'Picked by others',
    name: 'Kaisar Ahmed',
  },
  {
    id: 7,
    type: 'Device Offline',
    time: '08:20 PM, 20 Sep 2025',
    location: 'Office',
    address: '789 Maple Ave, CA',
    life: '2m05s',
    status: 'Picked by others',
    name: 'Kaisar Ahmed',
  },
  {
    id: 8,
    type: 'Device Offline',
    time: '08:20 PM, 20 Sep 2025',
    location: 'Office',
    address: '789 Maple Ave, CA',
    life: '2m05s',
    status: 'Picked by others',
    name: 'Kaisar Ahmed',
  },
  {
    id: 9,
    type: 'Device Offline',
    time: '08:20 PM, 20 Sep 2025',
    location: 'Office',
    address: '789 Maple Ave, CA',
    life: '2m05s',
    status: 'Picked by others',
    name: 'Kaisar Ahmed',
  },
  {
    id: 11,
    type: 'Device Offline',
    time: '08:20 PM, 20 Sep 2025',
    location: 'Office',
    address: '789 Maple Ave, CA',
    life: '2m05s',
    status: 'Picked by others',
    name: 'Kaisar Ahmed',
  },
  {
    id: 12,
    type: 'Device Offline',
    time: '08:20 PM, 20 Sep 2025',
    location: 'Office',
    address: '789 Maple Ave, CA',
    life: '2m05s',
    status: 'Picked by others',
    name: 'Kaisar Ahmed',
  },
  {
    id: 13,
    type: 'Fall Detected',
    time: '08:00 PM, 20 Sep 2025',
    location: 'Bedroom',
    address: '456 Elm Street, Suite 3, Los Angeles, United States',
    life: '46s',
    status: 'Unpicked',
    name: 'Majharul',
  },
];
